#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy-entry.sh — deploy the telemt-mgmt entry server (Xray dokodemo-door).
#
# Installs Xray via Docker Compose on a Russia-based entry server.  Xray uses
# a two-stage dokodemo-door inbound on port 443 (transparent TCP forward) so
# Telegram clients can connect via standard tg://proxy links.  Between the two
# stages a freedom outbound injects a PROXYv1 header (proxyProtocol:1) to
# preserve the real client IP.  The second stage routes into a VLESS-Reality
# outbound tunnel to the EU exit server.  The entry server has NO Reality keys
# of its own — it is a transparent TCP forwarder with PROXYv1 injection.
#
# Prompts for (first run; reads .env on re-run — INV-IDEMPOTENT):
#   EXIT_SERVER_IP    — IP/FQDN of the EU exit server
#   EXIT_VLESS_UUID   — VLESS UUID for the exit server's Xray inbound
#   EXIT_PUBLIC_KEY   — X25519 public key of the exit server's Reality
#   EXIT_REALITY_SNI  — SNI for the exit server's Reality (e.g. www.microsoft.com)
#   EXIT_SHORT_ID     — Short ID for the exit server's Reality
#
# Firewall: UFW allow 443/tcp only.
# Docker hardening: cap_drop ALL, read_only, no-new-privileges (INV-DOCKER).
#
# Idempotent: re-running reads existing .env and skips prompts.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Timing wrapper ───────────────────────────────────────────────────────────
# Records the start time and prints total elapsed on exit (for M1 measurement).
DEPLOY_START_TIME=$(date +%s)

finish() {
    local end_time elapsed
    end_time=$(date +%s)
    elapsed=$((end_time - DEPLOY_START_TIME))
    local mins=$((elapsed / 60))
    local secs=$((elapsed % 60))
    echo ""
    echo "━━━ Total elapsed time: ${mins}m ${secs}s ━━━"
}
trap finish EXIT

# ── Resolve script directory ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source shared helpers
# shellcheck disable=SC1091
source "$INFRA_DIR/lib/common.sh"

# ── Paths ───────────────────────────────────────────────────────────────────
ENV_FILE="$SCRIPT_DIR/.env"
XRAY_TEMPLATE="$SCRIPT_DIR/xray-config.json.template"
XRAY_CONFIG="$SCRIPT_DIR/xray-config.json"

# ── Pre-flight ──────────────────────────────────────────────────────────────
check_docker

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  telemt-mgmt — Entry Server Deploy (Xray dokodemo-door)      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo ""
echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  ⚠  RUSSIAN DATACENTER PROVIDER GUIDANCE                      │"
echo "│                                                              │"
echo "│  RECOMMENDED (Signal 1 not flagged):                         │"
echo "│    • Beget       — RU hosting, not on TSPU flagged list      │"
echo "│    • TimeWeb     — RU hosting, not on TSPU flagged list      │"
echo "│    • reg.ru      — RU hosting, not on TSPU flagged list      │"
echo "│                                                              │"
echo "│  ⚠  AVOID — Signal 1 flagged (June 2026 Siberian module):    │"
echo "│    • Selectel    — subnet flagged as Signal 1 (suspicious)   │"
echo "│    • Yandex.Cloud— subnet flagged as Signal 1 (suspicious)   │"
echo "│                                                              │"
echo "│  Signal 1 is always active on these subnets regardless of    │"
echo "│  SNI choice. Evasion depends on keeping Signals 2 & 3 clean. │"
echo "│  See TELEMT_FAKETLS_DOMAIN_RESEARCH_2026.md §1 and §6.       │"
echo "└──────────────────────────────────────────────────────────────┘"
echo ""

# ── Load existing config (idempotent re-run detection) ──────────────────────
# INV-IDEMPOTENT: if .env exists, values are loaded and prompt_for() skips prompts.
load_env "$ENV_FILE"

# ── Prompt for exit server configuration ─────────────────────────────────────
# The entry server is a transparent TCP forwarder — it has NO Reality keys,
# NO VLESS UUID, NO SNI of its own.  All tunnel credentials belong to the
# exit server and are generated by deploy-exit.sh on the exit server.

# EXIT_SERVER_IP — the EU exit server running telemt + Xray-exit.
EXIT_SERVER_IP="$(prompt_for "EXIT_SERVER_IP" "Enter exit server IP or FQDN")"
save_env_var "$ENV_FILE" "EXIT_SERVER_IP" "$EXIT_SERVER_IP"

# EXIT_VLESS_UUID — VLESS UUID for the exit server's Xray inbound.
# This is generated by deploy-exit.sh on the exit server and must be provided
# here so the entry server's VLESS outbound can authenticate to the exit.
echo ""
echo "Exit server VLESS-Reality tunnel configuration:"
echo "  The following values are generated by deploy-exit.sh on the exit server."
echo "  Run deploy-exit.sh first, then copy the output values here."
EXIT_VLESS_UUID="$(prompt_for "EXIT_VLESS_UUID" \
    "Enter exit server VLESS UUID (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_VLESS_UUID" "$EXIT_VLESS_UUID"

# EXIT_PUBLIC_KEY — X25519 public key of the exit server's Reality.
EXIT_PUBLIC_KEY="$(prompt_for "EXIT_PUBLIC_KEY" \
    "Enter exit server Reality public key (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_PUBLIC_KEY" "$EXIT_PUBLIC_KEY"

# EXIT_REALITY_SNI — SNI for the exit server's Reality.
# Default: www.microsoft.com (TKT-019 self-steal is deferred; this default is safe).
EXIT_REALITY_SNI="$(prompt_for "EXIT_REALITY_SNI" \
    "Enter exit server Reality SNI (default: www.microsoft.com)" \
    "www.microsoft.com")"
save_env_var "$ENV_FILE" "EXIT_REALITY_SNI" "$EXIT_REALITY_SNI"

# EXIT_SHORT_ID — Short ID for the exit server's Reality.
EXIT_SHORT_ID="$(prompt_for "EXIT_SHORT_ID" \
    "Enter exit server Reality short ID (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_SHORT_ID" "$EXIT_SHORT_ID"

echo ""
echo "✓ Configuration saved to $ENV_FILE"

# ── Generate Xray config from template ──────────────────────────────────────
echo "→ Generating xray-config.json from template..."

# Substitute exit-server placeholders in the template.
# Use sed with a delimiter unlikely to appear in keys/IDs.
sed \
    -e "s|__EXIT_SERVER_IP__|${EXIT_SERVER_IP}|g" \
    -e "s|__EXIT_VLESS_UUID__|${EXIT_VLESS_UUID}|g" \
    -e "s|__EXIT_PUBLIC_KEY__|${EXIT_PUBLIC_KEY}|g" \
    -e "s|__EXIT_REALITY_SNI__|${EXIT_REALITY_SNI}|g" \
    -e "s|__EXIT_SHORT_ID__|${EXIT_SHORT_ID}|g" \
    "$XRAY_TEMPLATE" > "$XRAY_CONFIG"

echo "✓ Generated $XRAY_CONFIG"

# ── Firewall: UFW allow 443/tcp only ────────────────────────────────────────
echo "→ Configuring firewall (UFW: allow 443/tcp)..."
if command -v ufw &>/dev/null; then
    # Allow SSH first to avoid lockout.
    ufw allow ssh &>/dev/null || true
    ufw allow 443/tcp &>/dev/null || true
    # Enable UFW if not already active (non-interactive).
    if ! ufw status | grep -q "Status: active"; then
        echo "  Enabling UFW..."
        ufw --force enable &>/dev/null
    fi
    echo "✓ UFW configured: 443/tcp allowed (SSH preserved)"
else
    echo "  ⚠ UFW not installed — skipping firewall configuration."
    echo "  Manual: sudo ufw allow ssh && sudo ufw allow 443/tcp && sudo ufw enable"
fi

# ── Deploy with Docker Compose ──────────────────────────────────────────────
echo "→ Starting Xray container via Docker Compose..."
cd "$SCRIPT_DIR"

if docker compose version &>/dev/null 2>&1; then
    docker compose down 2>/dev/null || true
    docker compose up -d
else
    docker-compose down 2>/dev/null || true
    docker-compose up -d
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✓ Entry server deployed successfully!                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "  Inbound:           0.0.0.0:443 (dokodemo-door — transparent TCP)"
echo "  PROXYv1:           enabled (freedom proxyProtocol:1)"
echo "  Tunnel:            VLESS-Reality → exit:443"
echo "  Exit server:       $EXIT_SERVER_IP"
echo "  Exit Reality SNI:  $EXIT_REALITY_SNI"
echo "  Fingerprint:       firefox (NOT chrome — blocked since May 2026)"
echo "  Entry Reality:     none (entry has no Reality keys of its own)"
echo ""
echo "  Re-run this script to update configuration."
echo ""
