#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy-entry.sh — deploy the telemt-mgmt entry server (Xray VLESS-Reality).
#
# Installs Xray via Docker Compose on a Russia-based entry server.  Xray
# terminates VLESS+Reality on port 443 from Telegram clients, then opens an
# encrypted VLESS-Reality tunnel to the EU exit server (running telemt +
# Xray-exit).  PROXYv1 (xver:1) preserves the real client IP through the
# tunnel so telemt sees the original client IP.
#
# Prompts for (first run; reads .env on re-run — INV-IDEMPOTENT):
#   EXIT_SERVER_IP        — IP/FQDN of the EU exit server
#   EXIT_VLESS_UUID       — VLESS UUID for the exit server's Xray inbound
#   EXIT_PUBLIC_KEY       — X25519 public key of the exit server's Reality
#   EXIT_REALITY_SNI      — SNI for the exit server's Reality (e.g. www.microsoft.com)
#   EXIT_SHORT_ID         — Short ID for the exit server's Reality
#   REALITY_SNI           — SNI for entry Reality (default: ads.x5.ru, Russian CDN)
#   REALITY_SNI_SECONDARY — Optional secondary serverNames entry (e.g. ya.ru)
#   REALITY_PRIVATE_KEY   — X25519 private key (auto-generate option)
#   REALITY_SHORT_IDS     — Comma-separated short IDs (auto-generate option)
#   VLESS_UUID_ENTRY      — VLESS UUID for the entry server's inbound (auto-gen)
#
# Firewall: UFW allow 443/tcp only.
# Docker hardening: cap_drop ALL, read_only, no-new-privileges (INV-DOCKER).
#
# Idempotent: re-running reads existing .env and skips prompts.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Timing wrapper ───────────────────────────────────────────────────────────
# Records the start time and prints total elapsed on exit (for M1 measurement).
DEPLOY_START_TIME=$(date +%s)

finish() {
    local end_time elapsed
    end_time=$(date +%s)
    elapsed=$((end_time - DEPLOY_START_TIME))
    local mins=$((elapsed / 60))
    local secs=$((elapsed % 60))
    echo ""
    echo "━━━ Total elapsed time: ${mins}m ${secs}s ━━━"
}
trap finish EXIT

# ── Resolve script directory ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source shared helpers
# shellcheck disable=SC1091
source "$INFRA_DIR/lib/common.sh"

# ── Paths ───────────────────────────────────────────────────────────────────
ENV_FILE="$SCRIPT_DIR/.env"
XRAY_TEMPLATE="$SCRIPT_DIR/xray-config.json.template"
XRAY_CONFIG="$SCRIPT_DIR/xray-config.json"

# ── Pre-flight ──────────────────────────────────────────────────────────────
check_docker

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  telemt-mgmt — Entry Server Deploy (Xray VLESS-Reality)      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── Load existing config (idempotent re-run detection) ──────────────────────
# INV-IDEMPOTENT: if .env exists, values are loaded and prompt_for() skips prompts.
load_env "$ENV_FILE"

# ── Prompt for configuration ────────────────────────────────────────────────

# EXIT_SERVER_IP — the EU exit server running telemt + Xray-exit.
EXIT_SERVER_IP="$(prompt_for "EXIT_SERVER_IP" "Enter exit server IP or FQDN")"
save_env_var "$ENV_FILE" "EXIT_SERVER_IP" "$EXIT_SERVER_IP"

# EXIT_VLESS_UUID — VLESS UUID for the exit server's Xray inbound.
# This is generated by deploy-exit.sh on the exit server and must be provided
# here so the entry server's VLESS outbound can authenticate to the exit.
echo ""
echo "Exit server VLESS-Reality tunnel configuration:"
echo "  The following values are generated by deploy-exit.sh on the exit server."
echo "  Run deploy-exit.sh first, then copy the output values here."
EXIT_VLESS_UUID="$(prompt_for "EXIT_VLESS_UUID" \
    "Enter exit server VLESS UUID (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_VLESS_UUID" "$EXIT_VLESS_UUID"

# EXIT_PUBLIC_KEY — X25519 public key of the exit server's Reality.
EXIT_PUBLIC_KEY="$(prompt_for "EXIT_PUBLIC_KEY" \
    "Enter exit server Reality public key (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_PUBLIC_KEY" "$EXIT_PUBLIC_KEY"

# EXIT_REALITY_SNI — SNI for the exit server's Reality.
# Default: www.microsoft.com (TKT-019 self-steal is deferred; this default is safe).
EXIT_REALITY_SNI="$(prompt_for "EXIT_REALITY_SNI" \
    "Enter exit server Reality SNI (default: www.microsoft.com)" \
    "www.microsoft.com")"
save_env_var "$ENV_FILE" "EXIT_REALITY_SNI" "$EXIT_REALITY_SNI"

# EXIT_SHORT_ID — Short ID for the exit server's Reality.
EXIT_SHORT_ID="$(prompt_for "EXIT_SHORT_ID" \
    "Enter exit server Reality short ID (from deploy-exit.sh output)")"
save_env_var "$ENV_FILE" "EXIT_SHORT_ID" "$EXIT_SHORT_ID"

# REALITY_SNI — default: ads.x5.ru (X5 Retail CDN, TSPU-whitelisted, production-validated Jul 2026).
# Secondary serverNames entry is optional (see REALITY_SNI_SECONDARY below).
REALITY_SNI="$(prompt_for "REALITY_SNI" \
    "Enter Reality SNI (default: ads.x5.ru — Russian CDN, TSPU-whitelisted)" \
    "ads.x5.ru")"
save_env_var "$ENV_FILE" "REALITY_SNI" "$REALITY_SNI"

# REALITY_SNI_SECONDARY — optional second serverNames entry for resilience.
# Idempotent: if already set in .env (including empty), re-run skips the prompt.
# When empty, serverNames contains only the primary SNI.
# When set (e.g. ya.ru), serverNames contains both primary and secondary.
# Check if key exists in .env (handles empty values correctly for idempotency)
if grep -q "^REALITY_SNI_SECONDARY=" "$ENV_FILE" 2>/dev/null; then
    REALITY_SNI_SECONDARY="${REALITY_SNI_SECONDARY:-}"
    echo "✓ REALITY_SNI_SECONDARY already set (from .env): ${REALITY_SNI_SECONDARY:-<not set>}"
else
    printf "Enter optional secondary Reality SNI (e.g. ya.ru, leave empty to skip): "
    read -r REALITY_SNI_SECONDARY
fi
save_env_var "$ENV_FILE" "REALITY_SNI_SECONDARY" "${REALITY_SNI_SECONDARY}"
export REALITY_SNI_SECONDARY

# REALITY_PRIVATE_KEY — auto-generate using xray x25519 if not provided.
# On re-run, prompt_for() returns the existing value from .env without prompting.
if [[ -n "${REALITY_PRIVATE_KEY:-}" ]]; then
    echo "✓ REALITY_PRIVATE_KEY already set (from .env)."
else
    echo ""
    echo "Reality private key generation:"
    echo "  The X25519 private key is used for Reality handshakes."
    echo "  You can provide your own, or auto-generate using 'xray x25519'."
    printf "Auto-generate Reality private key? [Y/n]: "
    read -r auto_gen
    auto_gen="${auto_gen:-Y}"
    if [[ "${auto_gen,,}" == "y" ]]; then
        echo "→ Generating X25519 keypair via xray x25519..."
        # Try to use xray binary if available; otherwise use docker.
        if command -v xray &>/dev/null; then
            KEYPAIR=$(xray x25519)
        else
            echo "  xray binary not found locally, using Docker..."
            KEYPAIR=$(docker run --rm ghcr.io/xtls/xray-core:latest xray x25519)
        fi
        # Output format: "Private key: <key>\nPublic key: <key>"
        REALITY_PRIVATE_KEY=$(echo "$KEYPAIR" | grep -i "Private" | awk '{print $NF}')
        REALITY_PUBLIC_KEY=$(echo "$KEYPAIR" | grep -i "Public" | awk '{print $NF}')
        echo "✓ Generated private key: ${REALITY_PRIVATE_KEY:0:8}...(truncated)"
        echo "  Public key (share with clients): $REALITY_PUBLIC_KEY"
    else
        printf "Enter Reality private key (X25519): "
        read -r REALITY_PRIVATE_KEY
        if [[ -z "$REALITY_PRIVATE_KEY" ]]; then
            echo "ERROR: REALITY_PRIVATE_KEY is required." >&2
            exit 1
        fi
    fi
    export REALITY_PRIVATE_KEY
fi
save_env_var "$ENV_FILE" "REALITY_PRIVATE_KEY" "$REALITY_PRIVATE_KEY"

# REALITY_SHORT_IDS — auto-generate if not provided.
# Short IDs are hex strings (typically 8 hex chars each).
if [[ -n "${REALITY_SHORT_IDS:-}" ]]; then
    echo "✓ REALITY_SHORT_IDS already set (from .env)."
else
    echo ""
    echo "Reality short IDs:"
    echo "  Short IDs are hex strings used for client routing."
    printf "Auto-generate Reality short IDs? [Y/n]: "
    read -r auto_ids
    auto_ids="${auto_ids:-Y}"
    if [[ "${auto_ids,,}" == "y" ]]; then
        echo "→ Generating short IDs..."
        REALITY_SHORT_IDS=$(generate_secret 4)
        # Add a second short ID (empty string "" is also valid in Xray)
        local_short_id=$(generate_secret 4)
        REALITY_SHORT_IDS="${REALITY_SHORT_IDS},${local_short_id}"
        echo "✓ Generated short IDs: $REALITY_SHORT_IDS"
    else
        printf "Enter Reality short IDs (comma-separated hex, e.g. ab12cd34): "
        read -r REALITY_SHORT_IDS
        if [[ -z "$REALITY_SHORT_IDS" ]]; then
            echo "ERROR: REALITY_SHORT_IDS is required." >&2
            exit 1
        fi
    fi
    export REALITY_SHORT_IDS
fi
save_env_var "$ENV_FILE" "REALITY_SHORT_IDS" "$REALITY_SHORT_IDS"

# VLESS_UUID_ENTRY — VLESS UUID for the entry server's inbound (client-facing).
# Auto-generate using xray uuid or uuidgen.
if [[ -n "${VLESS_UUID_ENTRY:-}" ]]; then
    echo "✓ VLESS_UUID_ENTRY already set (from .env)."
else
    echo ""
    echo "Entry VLESS UUID generation:"
    echo "  The VLESS UUID is used for client authentication on the entry inbound."
    printf "Auto-generate VLESS UUID? [Y/n]: "
    read -r auto_uuid
    auto_uuid="${auto_uuid:-Y}"
    if [[ "${auto_uuid,,}" == "y" ]]; then
        echo "→ Generating VLESS UUID..."
        if command -v xray &>/dev/null; then
            VLESS_UUID_ENTRY=$(xray uuid)
        elif command -v uuidgen &>/dev/null; then
            VLESS_UUID_ENTRY=$(uuidgen)
        else
            echo "  xray and uuidgen not found, using Docker..."
            VLESS_UUID_ENTRY=$(docker run --rm ghcr.io/xtls/xray-core:latest xray uuid)
        fi
        echo "✓ Generated VLESS UUID: $VLESS_UUID_ENTRY"
    else
        printf "Enter VLESS UUID for entry inbound: "
        read -r VLESS_UUID_ENTRY
        if [[ -z "$VLESS_UUID_ENTRY" ]]; then
            echo "ERROR: VLESS_UUID_ENTRY is required." >&2
            exit 1
        fi
    fi
    export VLESS_UUID_ENTRY
fi
save_env_var "$ENV_FILE" "VLESS_UUID_ENTRY" "$VLESS_UUID_ENTRY"

echo ""
echo "✓ Configuration saved to $ENV_FILE"

# ── Generate Xray config from template ──────────────────────────────────────
echo "→ Generating xray-config.json from template..."

# Format REALITY_SHORT_IDS as a JSON array body: "id1", "id2"
# The .env stores it as comma-separated hex; the template expects a bare
# JSON array body (no brackets) so we wrap each value in double quotes.
REALITY_SHORT_IDS_JSON=$(echo "$REALITY_SHORT_IDS" | sed 's/,/", "/g; s/^/"/; s/$/"/')

# Build REALITY_SERVER_NAMES JSON array body from primary + optional secondary SNI.
# When REALITY_SNI_SECONDARY is empty: "ads.x5.ru"
# When REALITY_SNI_SECONDARY is set:  "ads.x5.ru", "ya.ru"
if [[ -n "${REALITY_SNI_SECONDARY:-}" ]]; then
    REALITY_SERVER_NAMES_JSON="\"${REALITY_SNI}\", \"${REALITY_SNI_SECONDARY}\""
else
    REALITY_SERVER_NAMES_JSON="\"${REALITY_SNI}\""
fi


# Substitute placeholders in the template.
# Use sed with a delimiter unlikely to appear in keys/IDs.
sed \
    -e "s|__EXIT_SERVER_IP__|${EXIT_SERVER_IP}|g" \
    -e "s|__EXIT_VLESS_UUID__|${EXIT_VLESS_UUID}|g" \
    -e "s|__EXIT_PUBLIC_KEY__|${EXIT_PUBLIC_KEY}|g" \
    -e "s|__EXIT_REALITY_SNI__|${EXIT_REALITY_SNI}|g" \
    -e "s|__EXIT_SHORT_ID__|${EXIT_SHORT_ID}|g" \
    -e "s|__VLESS_UUID_ENTRY__|${VLESS_UUID_ENTRY}|g" \
    -e "s|__REALITY_SNI__|${REALITY_SNI}|g" \
    -e "s|__REALITY_SERVER_NAMES__|${REALITY_SERVER_NAMES_JSON}|g" \
    -e "s|__REALITY_PRIVATE_KEY__|${REALITY_PRIVATE_KEY}|g" \
    -e "s|__REALITY_SHORT_IDS__|${REALITY_SHORT_IDS_JSON}|g" \
    "$XRAY_TEMPLATE" > "$XRAY_CONFIG"

echo "✓ Generated $XRAY_CONFIG"

# ── Firewall: UFW allow 443/tcp only ────────────────────────────────────────
echo "→ Configuring firewall (UFW: allow 443/tcp)..."
if command -v ufw &>/dev/null; then
    # Allow SSH first to avoid lockout.
    ufw allow ssh &>/dev/null || true
    ufw allow 443/tcp &>/dev/null || true
    # Enable UFW if not already active (non-interactive).
    if ! ufw status | grep -q "Status: active"; then
        echo "  Enabling UFW..."
        ufw --force enable &>/dev/null
    fi
    echo "✓ UFW configured: 443/tcp allowed (SSH preserved)"
else
    echo "  ⚠ UFW not installed — skipping firewall configuration."
    echo "  Manual: sudo ufw allow ssh && sudo ufw allow 443/tcp && sudo ufw enable"
fi

# ── Deploy with Docker Compose ──────────────────────────────────────────────
echo "→ Starting Xray container via Docker Compose..."
cd "$SCRIPT_DIR"

if docker compose version &>/dev/null 2>&1; then
    docker compose down 2>/dev/null || true
    docker compose up -d
else
    docker-compose down 2>/dev/null || true
    docker-compose up -d
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✓ Entry server deployed successfully!                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "  Exit server:       $EXIT_SERVER_IP"
echo "  Encrypted S2:      VLESS-Reality tunnel (entry → exit:443)"
echo "  Exit Reality SNI:  $EXIT_REALITY_SNI"
echo "  Entry Reality SNI: $REALITY_SNI"
echo "  Secondary SNI:     ${REALITY_SNI_SECONDARY:-(none)}"
echo "  Listening:         0.0.0.0:443 (VLESS+Reality inbound)"
echo "  PROXYv1:           enabled (xver:1 — real client IP preserved through tunnel)"
echo "  Fingerprint:       firefox (NOT chrome — blocked since May 2026)"
echo ""
echo "  Re-run this script to update configuration."
echo ""
